[[customizations.filesystem]]
mountpoint = "/"
minsize = "20 GiB"

[[customizations.user]]
name = "admin"
password = "$6$rounds=4096$VfG.vJp5S$v6Y8R3sM7K8X1H9q0e5L2G4vJp5S.v6Y8R3sM7K8X1H9q0e5L2G4vJp5S"
groups = ["wheel"]
