[[customizations.filesystem]]
mountpoint = "/"
minsize = "20 GiB"

[[customizations.user]]
name = "admin"
password = "$6$VF9OGhdcgzxC2qs3$ptdToCi.HO0KNWIybUaLpZhPyLO2N6ErLw5jkN/.scCAHsh7h3/fwTvWxq7FuuV8IvfUQUB7Q6dF0mRYkEXPb."
groups = ["wheel"]
