[iso]
# Das Image, das auf die Festplatte installiert werden soll
image = "ghcr.io/humocs-man/sturdy-chainsaw:stable"
# Wir nutzen den schicken Readymade-Installer
installer = "readymade"

[live]
# Hier sagen wir Titanoboa, dass dein COSMIC-Image die Live-Umgebung stellt
base_image = "ghcr.io/humocs-man/sturdy-chainsaw:stable"
# Wichtig für COSMIC: Wir wollen direkt im Desktop landen
autologin = true

[installation]
# Hier verknüpfen wir deine disk.toml
config = "disk.toml"
