name: Build Custom ISO

on:
  workflow_dispatch:
  #schedule:
    #- cron: '0 0 * * 0'  # Weekly on Sunday

jobs:
  build-iso:
    name: Build ISO
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read
    
    steps:
      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v9
        
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Build ISO
        id: build
        uses: ublue-os/titanoboa@main
        with:
          image-ref: ghcr.io/humocs-man/sturdy-chainsaw:stable
          builder-distro: fedora
          
      - name: Rename ISO
        run: |
          mkdir -p output
          mv ${{ steps.build.outputs.iso-dest }} output/sturdy-chainsaw-$(date +%Y%m%d).iso
          (cd output && sha256sum *.iso | tee CHECKSUMS)
          
      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: sturdy-chainsaw
          path: output/
